name: textxd-2018-demos
channels:
  - conda-forge
dependencies:
  - jupyterhub==0.9.2
  - pandas
  - bokeh
  - scikit-learn
  - gensim
  - numpy
  - nltk
  - matplotlib
  - seaborn
  - requests
  - beautifulsoup4
  - lxml
